config:
  cluster:
    enabled: true
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 10Gi
        storageClassName: ionos-enterprise-ssd
  merge:
    accounts:
      $SYS:
        users:
        - password: pass
          user: sys
    # debug: true
    # trace: true
container:
  env:
    GOMEMLIMIT: 1500MiB
  merge:
    resources:
      limits:
        cpu: 500m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 128Mi
statefulSet:
  merge:
    spec:
      template:
        spec:
          initContainers:
          - command:
            - sh
            - -c
            - sleep 300
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            name: delay-startup
promExporter:
  enabled: true
  podMonitor:
    enabled: true
    merge:
      labels:
        release: kube-prometheus-stack